name: 'RedRays ABAP Security Scanner'
description: 'Scan ABAP code for security vulnerabilities using RedRays API'
author: 'RedRays Security'

inputs:
  api-key:
    description: 'RedRays API key (required)'
    required: true
  api-url:
    description: 'RedRays API URL'
    required: false
    default: 'https://api.redrays.io/api/scan'
  scan-dir:
    description: 'Directory containing ABAP files to scan'
    required: false
    default: '.'
  files:
    description: 'Comma-separated list of specific files to scan (overrides scan-dir)'
    required: false
  output-format:
    description: 'Report output format (csv, html, json)'
    required: false
    default: 'html'
  output-file:
    description: 'Report output file path'
    required: false
    default: 'redrays_security_report.html'
  fail-on-vulnerabilities:
    description: 'Fail the workflow if vulnerabilities are found'
    required: false
    default: 'true'
  threshold:
    description: 'Severity threshold for failing the build (critical, high, medium, low, informational)'
    required: false
    default: ''
  fail-on-api-errors:
    description: 'Fail the workflow if API errors occur'
    required: false
    default: 'false'

outputs:
  report-path:
    description: 'Path to the generated security report'
    value: ${{ steps.scan.outputs.report-path }}
  vulnerabilities-found:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.scan.outputs.vulnerabilities-found }}
  threshold-breached:
    description: 'Whether the severity threshold was breached'
    value: ${{ steps.scan.outputs.threshold-breached }}
  credit-error:
    description: 'Whether a credit error occurred'
    value: ${{ steps.scan.outputs.credit-error }}
  api-errors:
    description: 'Number of API errors that occurred'
    value: ${{ steps.scan.outputs.api-errors }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download RedRays ABAP Scanner
      shell: bash
      run: |
        curl -o redrays_scanner.py https://raw.githubusercontent.com/redrays-io/redrays-cicd/refs/heads/master/redrays_scanner.py
        chmod +x redrays_scanner.py

    - name: Run RedRays ABAP Security Scanner
      id: scan
      shell: bash
      run: |
        # Build command based on inputs
        CMD="python redrays_scanner.py --api-key ${{ inputs.api-key }} --api-url ${{ inputs.api-url }} --output-format ${{ inputs.output-format }} --output-file ${{ inputs.output-file }} --debug"
        
        # Add threshold parameter if specified
        if [ -n "${{ inputs.threshold }}" ]; then
          CMD="$CMD --threshold ${{ inputs.threshold }}"
        fi
        
        # Add either --scan-dir or --files depending on input
        if [ -n "${{ inputs.files }}" ]; then
          CMD="$CMD --files ${{ inputs.files }}"
        else
          CMD="$CMD --scan-dir ${{ inputs.scan-dir }}"
        fi
        
        # Run the command and capture exit code
        echo "Running: $CMD"
        $CMD
        SCAN_EXIT_CODE=$?
        
        # Set outputs
        echo "report-path=${{ inputs.output-file }}" >> $GITHUB_OUTPUT
        
        # Process exit codes
        case $SCAN_EXIT_CODE in
          0)
            echo "Scan completed successfully with no vulnerabilities found"
            echo "vulnerabilities-found=0" >> $GITHUB_OUTPUT
            echo "threshold-breached=false" >> $GITHUB_OUTPUT
            echo "credit-error=false" >> $GITHUB_OUTPUT
            echo "api-errors=0" >> $GITHUB_OUTPUT
            ;;
          1)
            # Vulnerabilities found that breach threshold
            if [ -f "${{ inputs.output-file }}" ]; then
              if [[ "${{ inputs.output-format }}" == "html" ]]; then
                VULNS=$(grep -o "Vulnerabilities Found: [0-9]*" ${{ inputs.output-file }} | awk '{print $3}')
              elif [[ "${{ inputs.output-format }}" == "json" ]]; then
                VULNS=$(grep -o '"files_scanned":.*' ${{ inputs.output-file }} | awk '{print $2}' | sed 's/,//')
              else
                # For CSV or other formats, count lines minus header
                VULNS=$(($(wc -l < ${{ inputs.output-file }}) - 1))
                if [ $VULNS -lt 0 ]; then VULNS=0; fi
              fi
              
              echo "vulnerabilities-found=$VULNS" >> $GITHUB_OUTPUT
              echo "Found $VULNS vulnerabilities that breach the threshold"
              echo "threshold-breached=true" >> $GITHUB_OUTPUT
              echo "credit-error=false" >> $GITHUB_OUTPUT
              echo "api-errors=0" >> $GITHUB_OUTPUT
              
              if [[ "${{ inputs.fail-on-vulnerabilities }}" == "true" ]]; then
                echo "::error::Security vulnerabilities detected that breach the threshold! See the report for details."
                exit 1
              fi
            fi
            ;;
          2)
            # No files scanned
            echo "vulnerabilities-found=0" >> $GITHUB_OUTPUT
            echo "threshold-breached=false" >> $GITHUB_OUTPUT
            echo "credit-error=false" >> $GITHUB_OUTPUT
            echo "api-errors=0" >> $GITHUB_OUTPUT
            echo "::warning::No ABAP files were found to scan"
            ;;
          4)
            # Credit error
            echo "vulnerabilities-found=0" >> $GITHUB_OUTPUT
            echo "threshold-breached=false" >> $GITHUB_OUTPUT
            echo "credit-error=true" >> $GITHUB_OUTPUT
            echo "api-errors=0" >> $GITHUB_OUTPUT
            echo "::warning::Insufficient credits in your RedRays account. Check the report for details."
            ;;
          *)
            # API errors or other issues
            echo "vulnerabilities-found=0" >> $GITHUB_OUTPUT
            echo "threshold-breached=false" >> $GITHUB_OUTPUT
            echo "credit-error=false" >> $GITHUB_OUTPUT
            echo "api-errors=1" >> $GITHUB_OUTPUT
            echo "::warning::Scanner encountered errors. Check the report for details."
            
            if [[ "${{ inputs.fail-on-api-errors }}" == "true" ]]; then
              echo "::error::API errors encountered during scanning! See the report for details."
              exit 1
            fi
            ;;
        esac